local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "ptBR")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["BORDER_COLOR"] = "Selecionar cor da borda"
L["CAST_BORDER"] = "Selecionar textura da borda"
L["FONT_SIZE"] = "Tamanho da fonte"
L["FRAME_LEVEL"] = "Nível de quadro"
L["GENERAL"] = "Configurações Gerais"
L["ICON_HIDE_BORDER"] = "Ocultar borda do ícone"
L["ICON_POS_X"] = "Posição do ícone X"
L["ICON_POS_Y"] = "Posição do ícone Y"
L["ICON_SIZE"] = "Tamanho do ícone"
L["LSM_TEXTURE_NOTE"] = "Nota: Se você usar uma textura/fonte personalizada de terceiros e excluí-la mais tarde do seu PC, precisará redefinir manualmente a textura ou fonte aqui para que o complemento continue funcionando."
L["NAMEPLATE"] = "Placa de identificação"
L["PARTY"] = "Grupo"
L["PLAYER"] = "Jogador"
L["POSXY_TOOLTIP"] = "Ajuste os valores de deslocamento XY para mover o quadro."
L["RESET_ALL"] = "Redefinir todas as configurações"
L["SHOW_TIMER"] = "Mostrar texto do temporizador"
L["STATUS_BG_COLOR"] = "Selecionar cor de fundo"
L["STATUS_CHANNEL_COLOR"] = "Selecionar cor de preenchimento do canal"
L["TEST_MODE_DRAG"] = "Modo de teste - Arraste para mover"
L["TEXT_COLOR"] = "Selecionar cor do texto"
L["TEXT_POS_X"] = "Posição do texto X"
L["TEXT_POS_Y"] = "Posição do texto Y"

